name: Update Market Indices

on:
  schedule:
    - cron: '0 1 * * *' # 每天 UTC 1:00 (北京时间 9:00) 运行
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cos-python-sdk-v5  # 安装腾讯云 COS SDK

      - name: Run update script
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          TENCENT_COS_REGION: ${{ secrets.TENCENT_COS_REGION }}
          TENCENT_COS_BUCKET: ${{ secrets.TENCENT_COS_BUCKET }}
        run: python update_market_indices.py
